[package]
name = "pow_consensus"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crypto = "0.5"
digest = "0.9"
sha2 = "0.10"
ethers = "2.0.10"
hex = "0.4" 